layout_spectrum: 0.2665446
typography_spectrum: 0.4371966
color:
  saturation: 0.0223825
  lightness: 0.2103314
  brandStrength: 0.6273199
  rhythmicContrast: 0.1570764
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Rgentile.artist
